### ISSUE TITLE
drf compound field incompatible with drf 3.10.x, needs a small upgrade

### ISSUE THREAD

**Issue by anveshagarwal** [estebistec/drf-compound-fields#29]
virtual/lib/python3.7/site-packages/drf_compound_fields/fields.py", line 10, in <module>
    
from rest_framework.compat import six
ImportError: cannot import name 'six' from 'rest_framework.compat' (virtual/lib/python3.7/site-packages/rest_framework/compat.py)

**Comment by estebistec** [comment]
First thing's first, let's get a new travis build that shows the failure. I'll take this opportunity to first specify more modern versions of python and then we'll go from there.

**Comment by estebistec** [comment]
As expected, the reported failure: https://travis-ci.org/estebistec/drf-compound-fields/jobs/587934794

I'll working on a patch a little later today.

**Comment by anveshagarwal** [comment]
thanks for the patch!!
